### PR TITLE
Fix urlhelper issue #56

### PR DESCRIPTION
**Pull request by smabuk**
Fix issue #56  by updating the new code to strip any unwanted characters rather than returning to the old method from StackOverflow.

### CODE REVIEW

**Comment by smabuk** [comment]
Should we be working off of dev or the project_VersionsAndRatings branch at the moment? Not sure which is the right branch for these pull requests? Seems like we strayed onto project_VersionsAndRatings for some unrelated things.

**Comment by csharpfritz** [comment]
Why do we need the extra replace statements?

**Comment by smabuk** [comment]
The issue was lgged by kim95748 yesterday. See the Issues #56

**Comment by csharpfritz** [comment]
Thanks for the help!

**Pull request merged**
