### PR TITLE
Getting pages service and repo free

### PR DESCRIPTION
**Pull request by bravecobra**
I moved a bit of code around ;)
All pages are now only using mediatr to convey request to the backend. There the handlers only route to the requests to an application service, which does the actual progressing of the request. There is no more leakage of domain objects into the UI. 
I've also used an abstraction package (cfr Microsoft.Extensions) to break the direct link between Application - Persistence. They just share interfaces, nothing more.

While not yet fully complete, it's a little step forward.

Left to do:

- [x] Remove the re-use of the article dto. This should be more specific per request
- [ ] Use automapper to map between dto's and viewmodels (this will clean out the pages even more)
- [x] Refactor Notifications (as it currently still uses the CoreWiki.Core, due to its settings)
- [x] Review the application code to find both reading and manage articles share code. They are different features with different concerns and should therefor be split. 
- [ ] Split the repositories based on the same feature responsibilities (cfr CQRS)

### CODE REVIEW

**Comment by bravecobra** [comment]
I'd like to leave the 2 remaining open items for some other pull request. They are basically the next cleanup step. Maybe create some separate issues for them? I don't to over-do this PR (too much)  😉

**Comment by bravecobra** [comment]
Closes #255

**Comment by bravecobra** [comment]
Closes #219

**Comment by bravecobra** [comment]
Closes #216

**Comment by bravecobra** [comment]
Closes #215

**Comment by bravecobra** [comment]
Closes #214

**Comment by bravecobra** [comment]
Closes #64

**Comment by bravecobra** [comment]
Closes #173

**Comment by csharpfritz** [comment]
Thank you very much for this awesome contribution!

**Pull request merged**
