### PR TITLE
Added backlog of videos and Architecture series

### PR DESCRIPTION
**Pull request by Amoenus**
These may need time marks added for convenience, but it would take me too much effort at the moment.

---
This change is [Reviewable](https://reviewable.io/reviews/csharpfritz/corewiki/307)

### CODE REVIEW

**Comment by csharpfritz** [comment]
We have a YouTube playlist for this... and I think it would work more nicely in the GitHub Wiki, as we will be updating it frequently and it does not impact the source code.

Or maybe we should start a docs folder and load items like this into there.  That might be a good place as well.  I just feel like the README is getting a bit crowded

**Comment by Amoenus** [comment]
Fair point. Well, at least we have that list in markdown. ready to be copied wherever it needs to go ^_^

**Comment by csharpfritz** [comment]
Completely agreed..  This solves part of the bigger problem of documenting Corewiki, and we need to spend some time on both docs and more tests

**Comment by csharpfritz** [comment]
Thanks for the contribution!

**Pull request merged**
