### PR TITLE
Update-> Cake 0.30.0 & .NET SDK2.1.401

### PR DESCRIPTION
**Pull request by devlead**
* Update to Cake 0.30.0
* Update to .NET SDK 2.1.401
* Update Docker runtime image to 2.1.3-aspnetcore-runtime
* Fix line ending for bash files which broke by c371acae0a200980bf3351a6078f45353ea4208e
   - Works on my CI ™️ [Build Status](https://travis-ci.org/devlead/CoreWiki/builds/422552652)
* Added install SDK if missing ( Sorts AppVeyor being behind )
* Sets TLS 1.2 in build.ps1 as it's now required, but some powershell installs still default to older version.

Cake 0.30.0 mean it can be built and boostrapped easy 
```bash
dotnet tool install -g Cake.Tool
```

...and when tool is installed you can just enter repo and typ
```bash
dotnet cake
```

Read more at
https://cakebuild.net/blog/2018/08/cake-v0.30.0-released
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install

### CODE REVIEW

**Comment by devlead** [comment]
GH having issues commit 300cbe70f102b455b22d9d6d5fecd8856964d15b is incoming which will sort the AppVeyor issue, 

Travis builds fine after I added 94dff2ef83ba12c778906671e4b810541f9e2cd3

**Comment by devlead** [comment]
Appveyor couldn't fetch from GH so might need to hit rebuild.

**Comment by devlead** [comment]
Worked fine here
https://ci.appveyor.com/project/devlead/corewiki/build/1.0.16
😎

Should add travis to test unix bits, works fine on my "Travis" now
https://travis-ci.org/devlead/CoreWiki/builds/421625481

**Comment by smabuk** [comment]
@devlead Given that you moved the docker image to 2.1.3 shouldn't the SDK version be 2.1.401 (which is where 2.1.3 was introduced)?

**Comment by devlead** [comment]
@smabuk yes, will address that.

**Comment by devlead** [comment]
Updated and cleaned up PR.

**Comment by csharpfritz** [comment]
Thank you very much for the update.. its great to stay current!

**Pull request merged**
