### PR TITLE
Use static data to prevent migrations confusion

### PR DESCRIPTION
**Pull request by ashleybroughton**
Temporarily workaround #191 migration issue by using static data for homepage article, until we decide on what to do.

**Database should be regenerated from scratch or manually modified with the empty guid and specific date value before adding further migrations**

The code in `ApplicationDbContextModelSnapshot.cs` is EF generated, so we can't replace this with `Guid.Empty` unfortunately.

### CODE REVIEW

**Comment by ashleybroughton** [comment]
Should we be using Migrations to seed data?

If we put these things in the actual SeedData method they wouldn't be included in the migration Up/Down/Designer code, right?

**Comment by ashleybroughton** [comment]
This will conflict with Parithon's update in #194 . So I will fix these up once that's merged.

**Comment by parithon** [comment]
I'm new to Github so I have no idea if this is possible, but it would be awesome if we could work off each other's PRs prior to them being merged into Fritz' repo so we don't have to wait. Have any experience with that?

**Comment by ashleybroughton** [comment]
@parithon I think the easiest way to do that for either person, is to pull the changes from the other persons forked branch, then when they've changed it, submit a PR to that fork, instead of the core repo.

**Comment by ashleybroughton** [comment]
Note, I do not know whether this is the correct way to do things, but it seems it would work supposing the other person merges the commits.

I often find myself waiting to work on features because I want the changes of another PR to go through first to either help with what I'm doing, or to reduce merge conflicts.

It would be good to know the correct process for doing this kind of thing.

**Comment by parithon** [comment]
@ashleybroughton I'll merge this in tonight. Hopefully you'll get the credit on the leaderboard too... Suppose we'll find out tomorrow.

**Comment by ashleybroughton** [comment]
I'm not too worried about the credit. Just want to help move the project forward.

**Pull request closed without merging**
