### PR TITLE
Moved the UrlHelpers class into class accessible by the Article class.

### PR DESCRIPTION
**Pull request by lythix**
Removed the offending duplicated method in the Article class.

First real look at the code base, hopefully the new location is not going against its intention. 
Might also be an idea to move some other helpers like the StringHelpers?

### CODE REVIEW

**Comment by bravecobra** [comment]
I don't think the UI should be using anything of the Core directly. So anything in the CoreWiki.Pages should not reference the CoreWiki.Core namespace. As mentioned on stream, any urlhelper related code should be passed to the application layer where it in turn will call the real UrlHelper code. Thus we can remove the direct dependency to UrlHelpers from the UI. We can do that by moving the validation to the application layer as well.
Your current code is reintroducing the dependencies I tried to remove earlier. The fact that the duplicate code is still there is due to the validation still being in the UI layer instead of the Application layer. So imho we should move the validation and then remove the duplicate code.
Hope this helps.

**Comment by lythix** [comment]
I'll have another look at this with that extra info. 
Sounds like the UI should not have a reference to CoreWiki.Core project at all.

**Comment by lythix** [comment]
Removed the reference to CoreWiki.Core from Pages. 

Added a Constants file with duplication of the HomePageSlug, then saw pretty much same fill in another branch. Relocated Constants file into CoreWiki.Application project. 

I could not locate the validation being done in the UI layer but I'm sure I'll find that as I get more familiar with where things are.

**Comment by csharpfritz** [comment]
This addresses #313

**Comment by csharpfritz** [comment]
We've reviewed and implemented this feature.  Thanks for getting us started talking about it

**Pull request closed without merging**
