### PR TITLE
Fixed paginator logic errors

### LINKED ISSUE #160: [Bug] Paginator next and last buttons clickable when no articles available
Discovered during auditing of #120 

Logic needs to be adjusted so that buttons are not clickable when there are no further articles to browse to.

image

### LINKED ISSUE #161: [Bug] Paginator buttons incorrectly enabled when page number manipulated
https://localhost:44333/all/0

image

### PR DESCRIPTION
**Pull request by ashleybroughton**
Fixes #160 
Fixes #161

### CODE REVIEW

**Comment by parithon** [comment]
Would it be better aesthetically to remove the button entirely if it isn't clickable?

**Comment by ashleybroughton** [comment]
@parithon that is what google does. If we decide to go this route we would need to put spacers in their place, otherwise the user will experience an unexpected jump when navigating.

image

The spacer would change the navigation to look like this, but I'm not sure whether the gap is aesthetically pleasing as opposed to a disabled button.

image

What does everyone think is the best way to have the paginator buttons?

**Comment by emo333** [comment]
@ashleybroughton You are a frickin machine!  ;)

I'm not really a fan of the << >> goto first/last buttons in paginators from a UI experience it really seems to be a waste of space for the actual usefulness of being able to quickly go to first/last pages.

**Comment by ashleybroughton** [comment]
I agree that the additional navigation buttons don't really provide much to the navigation experience. Though displaying a max of 1 of 2 paginator links paginator max pages display of 1 or 2, they become absolutely necessary (though I'm not sure why someone would opt to have such a small paginator).

With a paginator size of 2 pages, you would be able to navigate forward, but never back (until the last page). 

image

You could also choose to have no page links at all, and just use navigators.

image


Perhaps it would be better to add an additional attributes to the `<markdown..>` tag to specify whether or not to show the first/previous/next/last buttons.

**Comment by csharpfritz** [comment]
Thanks for fixing this up, and I like the discussion about how to configure the pager

**Comment by csharpfritz** [comment]
Created issue #167 to track the configuration of the pager feature

**Pull request merged**
