### PR TITLE
Updates to dark theme css

### LINKED ISSUE #251: MyRoles doesn't look right in other themes
In dark theme, the MyRoles page needs some help:  https://localhost:8081/identity/account/manage/myroles

### PR DESCRIPTION
**Pull request by cmjchrisjones**
Minor tweaks to the dark theme css

Closes #251

### CODE REVIEW

**Comment by csharpfritz** [comment]
This looks nice, but you've updated the CSS files, and not the SCSS.  Next time we rebuild, the CSS will be overwritten by the compiled SCSS.  Let's get the themeDark.scss updated and this will persist across builds.

**Comment by smabuk** [comment]
If you take a look at the file `node_modules\bootstrap\scss\_variables.scss` you'll see all of the easily overridable Bootstrap variables used for customizing the styles easily.

So placing the line `$hr-border-color: white !default;` in the file themeDarks.scss will be equivalent to the first change you made. 

Most of the changes you made can be accomplished this way, and we already have some of the colors already defined.

**Comment by cmjchrisjones** [comment]
@csharpfritz , oops :),

@smabuk, Thanks for the tip 👍

I've not used SCSS before so I'll take a look and update this PR accordingly

**Comment by cmjchrisjones** [comment]
Hi @csharpfritz and @smabuk 

I’ve tried the suggestions of updating the scss file. 

However doing this doesn’t seem to update the generated css (even after cleaning/rebuilding) or manually deleting the generated css files. 

I maybe wrong but I’ve looked in the compilerconfig.json  and it looks like it should output but doesn’t seem to be. 

I’ve tried installing and using the webcompiler extension to recompile, and using the NPM task runner but both gives me rgba errors (one line 301 of themedark.scss, the file only has 93! this was on a new branch of dev) so I’ve now got totally lost!

I’ve tried following @smabuk’s guide but I don’t seem to be able to get it working. 

I’ve had a look at the readme’s and I don’t see any specific install extensions required, not sure if I’ve stumbled across a bug of kind or if I’ve missed something. 
SASS is all new to me so might be a pre-requisite I’ve not got installed…

I'm happy to raise it as a new issue if you think it maybe a bug?

**Comment by erwindevreugd** [comment]
Webcompiler should work, I think the line number difference comes from the imports in themedark.scss

```css
@import 'custom-variables';

@import '../../node_modules/bootstrap/scss/bootstrap';

@import 'custom-styles';
```
Maybe they increment the line numbers.

**Comment by cmjchrisjones** [comment]
@csharpfritz Is this OK? I finally figured out my 'numpty' issue which was causing me a weird error! 

Way back when I initially started I had 'accidentally' manually updated one of the scss files in the node_modules folder. 🤦‍♂️ 

However I have now got the scss compiling and updating the css and the min.css files (I'm not sure if these were supposed to be committed along with the scss file (but they didn't seem to be ignored by default so I've included them in for the ride).

Also a shout out to VS Code as it was a combination of that and an extension called _Live Sass Compiler_  that gave me a 'proper' stack trace error message allowing me to trace back to where my original error had occurred, which unfortunately full VS didn't give the same level of info!

**Comment by csharpfritz** [comment]
@cmjchrisjones I'll take a look on tomorrow's stream and we can go from there

**Comment by cmjchrisjones** [comment]
Thanks, I probably won’t make the live stream as it will be during my work hours but I’ll try to catch up after

**Comment by smabuk** [comment]
@cmjchrisjones whilst what you have created would have the desired effect in this situation, the Bootstrap way would be to do something like the following:

In ```themeDark.scss```, before the ```@import```:

```
$card-border-color:   $light !default;
$list-group-bg:       $dark !default;
$hr-border-color:     $white !default;
```

This avoids having the styles created twice; once by Bootstrap and once at the end of the file by us (this is the reason ```!important``` was required in your code).

**Comment by csharpfritz** [comment]
Thank you for following up and completing this.  Looks great !

**Pull request merged**
