### PR TITLE
Automate the creation of libraries under wwwroot/lib from node_modules

### PR DESCRIPTION
**Pull request by smabuk**
After the last stream I went off to upgrade the external packages on my own sites to the latest versions and decided to automate it this time.

This automates the mirroring of libraries to **wwwroot/lib/...** from **node_modules/...**
I've recreated the same **dist** folder structure under each package, but not recreated the .map files.

It uses the bundling and minification package which is already used by default in ASP.NET Core 2.0 packages so it should work for everyone.

## Extra Benefit ##
As an added benefit I was able to to create a simple method for customising the Bootstrap 4 and therefore the site theme via SCSS. This method gives access to the mixins and variables that Bootstrap uses natively; therefore making it really easy to customize.

I've used this to make 1 small change as an example the navbar should look a very dark blue.

The original idea for this came from the Bootstrap Theme Kit at [HackerThemes](https://hackerthemes.com) although I've simplified his process.

## Issues ##
The library files get recreated with each restore or build and despite the fact that git diff shows no differences all of the copied files shows as modified and pending commit.

- **This isn't happening on any of my other projects using this exact same technique.**
    - Is there a project or git setting within this project causing this behaviour?
    - Is this only happening on my machine, because it happens on master with simplemde as well?
    - Anyone seen this?

### Issues Update ###
When these files are staged to GitHub they vanish from the list. They don't get checked in at all if they haven't changed!

- ~~Makes commit all tricky~~
- ~~Should they be removed from source control as they are just copies of external libraries?~~
    - ~~If they are removed and the package is no longer available we won't be able to compile!~~
    - ~~Is keeping deployed release versions enough to meet these needs?~~

### CODE REVIEW

**Comment by smabuk** [comment]
Current conflicts occur because I mirrored the structure used by the moment library whereas the files got placed into the lib/moment root during the stream

package.json has extra packages in the pull request to handle popepr, jquery and jquery validation etc.

**Comment by smabuk** [comment]
@csharpfritz Could you take a look and see if you are seeing the same behaviour as the _issues_ on your machine? It may be something about my environment I'm not aware of.

**Comment by smabuk** [comment]
## Bootstrap 4.1 ##

I've run into 1 issue with Bootstrap v4.1.0.

Bootstrap has deprecated `text-hide()` using a `@warn` declaration in the file mixins\_text-hide.scss .
My set-up is treating this as a reason not to compile and output the final css, but deleting this line from the source will fix it.

**Comment by csharpfritz** [comment]
Thank you for the contribution... this should make adding and updating our libraries so much easier!

**Pull request merged**
