### PR TITLE
Feature extensibility

### PR DESCRIPTION
**Pull request by erwindevreugd**
Expended on extensibility started by @csharpfritz and @miguelcastro67.

I mainly did this because I liked this extensibility architecture by @miguelcastro67 and I wanted to learn from it. So if @csharpfritz has other plans to do something on-stream with Miguel feel free to ignore this PR.

* Changed the loading of ```CoreWikiModules``` through reflection instead of the configuration file. (this assumes that only administrators/authorized people would have access to the CoreWiki installation)
  * The basic idea is:
    * It looks in the root of CoreWiki for CoreWiki for internal modules (Modules included with CoreWiki).
    * It looks in CoreWiki_Root\CoreWikiModules for external (3rd party) modules.

* Implemented events for:
  * Pre-account creation (passes no values as I'm not sure we will want to pass account information to external modules)
  * Post-account creation (passes no values as I'm not sure we will want to pass account information to external modules)
  * Pre-article creation.
  * Post-article creation.
  * Pre-acrticle edit.
  * Post-article edit.
  * Pre-comment creation.
  * Post-comment creation.

(Only create pre/post article are currently hooked up within the relevant page so this PR doesn't interfere with the refactoring of the data handling)

### CODE REVIEW

**Comment by nmalocic** [comment]
Hi @erwindevreugd could you explain what is problem with passing account data to 3rd parties?
I see how it can be dangerous, but i think that all "third party" software in case of Wiki is .dll files someone hosting the app put there. So if i understood workshop, i took basic functionality and i wanna force that all users on wiki use company email, or enforce some special password policy.

How would i extend this application in that case?

Thanks in advance!

**Comment by erwindevreugd** [comment]
Sure, 
I think there needs to be some discussion first before doing something that might be a security risk or a violation of regulations.

With regards to security: the administrator of the CoreWiki installation is in control of what dll's are installed but not of what happens within the dll's.
With regards to regulations: I don't know if sharing an email address with a third party library for instance is allowed under GDPR.

So if the general consensus is that it is not a problem we can add additional features/events/data.

**Comment by nmalocic** [comment]
I agree that there should be discussion (i guess Jeff will decide :) ) 
And for GDPR part i guess no one knows for sure.

**Comment by erwindevreugd** [comment]
Moved discussion to #224

**Comment by nmalocic** [comment]
Hi @erwindevreugd  sorry for bothering you but i have few more questions ( i think most of them are my lack of .net core experience) 

1. In the ApplicationBuilderExtensions.cs you just say:
`var extensibilityManager = applicationBuilder.ApplicationServices.GetService(typeof(IExtensibilityManager));`
this will instantiate manager and let DI inject it where it's needed?

2. What was your idea behind ExtensibilityManagerBase, and why is OnRegisterCoreWikiModules empty in abstract class?
Could we move ModulesPath, coreWikiModuleHost and moduleLoader to base class and have that logic abstracted? And implementation will see them as protected and can override method and ModulesPath if needed? ( I can be totally off here :( )

3. Why is re throwing exception from extensibility  modules breaking the app?

Again sorry for bothering you.

**Comment by erwindevreugd** [comment]
Hi @nmalocic 
That's no problem! Code reviews are a good thing and I am also still learning.

1. The issue I ran into is with the ```CoreWikiModuleLoader``` which is part of the ```ExtensibilityManager```, the ```CoreWikiModuleLoader``` has to load dll's from disk (which can take a while). Both are registered as singletons in DI but are not instanciated until they are first needed, normaly this would be on the first page request. I didn't want the first request to be slow when we're loading a lot of modules so I added the ```GetService``` to force the ```CoreWikiLoader``` to load modules at application startup. There might be a better way of ensuring this.

2. I guess I was thinking of allowing module developers to create their own ```ExtensibilityManager``` with a different way of loading the modules. Which I now think would be better to allow them to create a different ```CoreWikiModuleLoader``` or it might not even be a good idea at all. The ```OnRegisterCoreWikiModules``` method body is empty because I should have made it abstract instead of virtual. ```CoreWikiModuleHost``` and ```ModuleLoader``` are already passed to the base class but ```ModulePath``` and ```OnRegisterCoreWikiModules``` could be moved to the base class.

3. If the exception is not handled within the page that is calling the ```ExtensibilityManager``` the application will crash. Since we are already logging the exception within the ```ExtensibilityManager``` I didn't see a reason to let the exceptions through to the page. This will likely change when Mediatr is implemented as you will want to handle exceptions within the Mediatr request handler. (At least that is what I do in my own projects)

**Comment by csharpfritz** [comment]
Thanks so much for the contribution... this is great, and moves us closer to having a robust extensibility model

**Pull request merged**
