### PR TITLE
'Article not found' and 'Page not found' error pages (Issue 13)

### PR DESCRIPTION
**Pull request by pete-a**
This PR aims to implement the wiki page not found issue https://github.com/csharpfritz/CoreWiki/issues/13

I've intentionally created two error pages. The first is for when the URL is a missing article slug (e.g `/a-non-existing-article`). This will show the 'Article not found' error page. The other 404 error page is is for more generic 404s (e.g `/some/url/that-does/not/exist`).

I would be grateful for any feedback, specifically:
- Any changes to the text in the 404 pages
- Is the `ArticleNotFound` ViewResult class a good approach? And should it be in the `CoreWiki.Helpers` namespace or elsewhere?

P.S @csharpfritz my apologies for my first two PRs (the tabs and editorconfig) today. I was apprehensive about committing a PR to the project and I thought a small code tidy (e.g the boy scout rule) could be a way to get started. I didn't mean to cause you frustration at the start of your week, rather I was trying to help but in hindsight I definitely didn't go the right way about it

### CODE REVIEW

**Comment by DevOpsChallengeBr** [comment]
@pete-a,  Very cool the way you solved the problem. Until this moment, I did not know that I could create a custom ViewResult and replace the return of NotFound by it. 

Thank you for sharing the knowledge.

I would like to suggest, if possible, remove the last commit once it treats a problem in Edit functionality. The problem in the edit was merge and this Treaty in PR (#84 Fix Edit/Save continues not working)

**Comment by pete-a** [comment]
Thanks @DevOpsChallengeBr :). Re the change: sure thing. 
Just to make sure I'm on the right page, do you mean in `Edit.cshtml.cs`, change the `ArticleNotFoundResult()` (lines 36 & 62) back to regular `NotFound()` view results?

**Comment by DevOpsChallengeBr** [comment]
No @pete-a , undo only the following change:

**FROM** --> `Article = await _context.Articles.SingleOrDefaultAsync(m => m.Id == id);`
**TO** --> `Article = await _context.Articles.SingleOrDefaultAsync(m => m.Topic == id);`

**Comment by pete-a** [comment]
@DevOpsChallengeBr ah ok I see what you mean. 
Again to confirm:
`Article = await _context.Articles.SingleOrDefaultAsync(m => m.Id == id);` is currently on the dev branch (https://github.com/csharpfritz/CoreWiki/blob/dev/CoreWiki/Pages/Edit.cshtml.cs#L32)

But you want me to change it back to what it was before PR https://github.com/csharpfritz/CoreWiki/pull/76 was merged into dev?

To do that I will also need change the type of the `id` argument to a string. E.g:
FROM: `public async Task<IActionResult> OnGetAsync(int id)`
TO: `public async Task<IActionResult> OnGetAsync(string id)`

My only concern is that if I do that and this PR gets merged before yours (https://github.com/csharpfritz/CoreWiki/pull/84), won't it inadvertently undo the fix in PR https://github.com/csharpfritz/CoreWiki/pull/76 that's already on the dev branch?

Sorry if I'm missing something here

**Comment by DevOpsChallengeBr** [comment]
@pete-a , Sorry, you're correct. I thought you'd changed.

**Comment by csharpfritz** [comment]
Thanks for the contribution!  This looks good and makes it easy to protect our site visitors from going somewhere they shouldn't

**Pull request merged**
