### PR TITLE
Refactored the Migrations to the CoreWiki.Data project & other fixes

### LINKED ISSUE #193: ApplicationDbContext Migrations Broken
When we refactored the `ApplicationDbContext` out of the CoreWiki project to it's own CoreWiki.Data project migrations no longer work.

### PR DESCRIPTION
**Pull request by parithon**
This fixes #193.

Merged the fixes @ashleybroughton suggested for the Migrations issue in #192.

Added an MSBuild target to ensure the NPM packages are downloaded prior to the Bundler running. This will ensure the JavaScript libraries we rely on are available on a fresh clone.

### CODE REVIEW

**Comment by ashleybroughton** [comment]
Hey @parithon, I looked at doing this, but each time I tried to move the Migrations to the other project the file grouping / nesting stopped working. Did you face this issue also?

image

**Comment by parithon** [comment]
Hi @ashleybroughton. Yes, when moving the folder VS doesn't respect the nesting in the solution explorer but that shouldn't effect the build any.

**Comment by parithon** [comment]
Doing a little more research, File Nesting is only available to ASP.NET Core projects which explains why the nesting isn't working when moving them to the other project. Here is the Microsoft Doc talking about file nesting: https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer

**Comment by parithon** [comment]
I'll be interesting to see if @ashleybroughton gets recognition on the leaderboard for her work on this PR. Thanks @ashleybroughton!

**Comment by ashleybroughton** [comment]
"their work" please @parithon. Inclusive language is encouraged.

**Comment by csharpfritz** [comment]
Thanks so much for moving this...  it feels like its now  residing in the proper location.

**Pull request merged**
