### PR TITLE
Introduced StyleCop for keeping the code clean, neat and tidy

### PR DESCRIPTION
**Pull request by cmjchrisjones**
Apologies for the mammoth PR!

I believe someone last week bought up the issue of trying to keep the code base clean and consistent. I have added in StyleCop and gone through most of the rules and set the error level, and (maybe controversially) set the build to fail where rule(s) aren't met)

I hope you think this was  a worthwhile change.

NB. There is currently an ongoing discussion around StyleCop rules and RazorPages naming conventions (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2590#issuecomment-355010530), therefore I've 'disabled' these individually for the PageModels.

### CODE REVIEW

**Comment by cmjchrisjones** [comment]
I’m a little bit stumped on why AppVeyor isn’t building. It currently builds locally using MSBuild via VS2017, dotnet build via command line and also I’ve tried cake using the build.ps1 file which are all fine and successful locally.

I’m hoping to catch the stream live today but I may miss the first 20-30 minutes

**Comment by HenryMigo** [comment]
@cmjchrisjones

 `
dotnet.exe : npm ERR! request to https://registry.npmjs.org/bootstrap failed, reason: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, 
DNS:a.sni.global-ssl.fastly.net"
`

There seems to be a dot at the end of '`registry.npmjs.org`' could this be the issue?

**Comment by cmjchrisjones** [comment]
@HenryMigo, wasn't anything to do with that, no text of that nature anywhere in the solution!

I did have some other errors/warnings in visual studio which I had disregarded as it was building locally and only seemed related to JavaScript errors. Fixed those and now its building on AppVeyor, so either that has fixed it or it was just a blip with AppVeyor at the weekend. 

Unfortunately no a clear error message coming from AppVeyor but its building now, which is the main thing. Would still be nice to know however if there is a way of just kicking off another build without having to make another commit.

We used to have something similar at my work with Stash and Jenkins, where if a build failed we could just add a comment of **test this please** to a PR in stash which would queue another build on Jenkins, not sure if that's possible on this setup though.

**Comment by cmjchrisjones** [comment]
Hi @csharpfritz  - completely understand your earlier comments from when I first opened this PR, in hindsight I should have created an issue etc before raising this - still getting used to all this open-source etiquette - mental note made for future :). 

I believe on Tuesday you said this may be discussed a bit more on stream today with guest, I was hoping to try and get these merge-conflicts resolved ready for it but I've run out of time, not sure if I'll be able to make the stream either today as I'm at work but I might try to drop in depending on how good my network connectivity is, if not I shall be catching up later.

**Comment by cmjchrisjones** [comment]
Hi @csharpfritz, hopefully this is OK. Based on the recent discussions I've now updated this PR so that:

- Stylecop is added into each project in the solution
- There is a StyleCopRuleset at solution level rather than at project level
- All violations are just shown as warnings rather then errors
- All warnings are reset to StyleCop's defaults (apart from I've set SA1027 rule to off as that was a warning about not using tabs as the editor config is set to use tabs)

**Comment by csharpfritz** [comment]
Sorry, I can't accept this as it is a bit too much of a change to the entire project.

Perhaps we can just introduce the rulesets with no breaking changes, but only warnings and start to slowly adhere to those rules

**Pull request closed without merging**
