### PR TITLE
Implemented issue#2

### PR DESCRIPTION
**Pull request by summer600**
Added Identity using the live stream sample code from 24-04-2018 with Scott Hunter. I did not copy over the Photo's addition. I did not add security attributes to all required pages such as create new article and edit article. But wanted to create the pull request before anther livestream updates dev

### CODE REVIEW

**Comment by summer600** [comment]
If you want I can commit this with a rebase to project_VersionsAndRatings, I have it in my workspace (sorry for the TFS lingo :-)  )

**Comment by csharpfritz** [comment]
Let's take another look at this pull request... can you move the new feature into a separate branch and then pull just that feature?  There's too much merging and changing going on in here

**Comment by csharpfritz** [comment]
Lets move this to another pull request with only the changes to support this feature

**Comment by summer600** [comment]
Will rebase but haven't got the time this weeekend. It was open for quite some time and hence got behind. Should I rebase on master or on the project_Versionsandratings I first used the current Dev but since ratings was ahead I rebased on that :-( I now hear in the stream (replay on youtube) that you prefer DEV so will try and rebase on DEV current head..
No worries It's usually busy during the stream so you don't get to merging all pull requests.

**Comment by csharpfritz** [comment]
Let's rebase on the DEV branch.

Thanks!



Jeff

**Comment by summer600** [comment]
I was not sure of the rebase command, even after using the visualizer from the workshop. I'm not a git power user so I did an update of my dev from your upstream, then a merge from dev to my issue2. That gave a few conflicts which I manually merged keeping you changes and  manually reading mine. 
On a side note: I love (and miss) the three way conflict resolve windows from TFS and don't really like the <<< HEAD stuff git does.

**Comment by csharpfritz** [comment]
I'm sorry, but another pull request that delivers this more cleanly has been received, and I'm going to take that PR.

Thanks for your interest, let's work on more code together

**Comment by summer600** [comment]
A well, it gave me something to do and learn some git :-)
At least security is now included in the wiki which enables a lot of new features that all were waiting on a "user"

**Comment by csharpfritz** [comment]
I completely agree.. 

User profile will be needed soon. 



Jeff

**Pull request closed without merging**
