### PR TITLE
Pager TagHelper update

### PR DESCRIPTION
**Pull request by smabuk**
## TagHelper Update ##
Updates the TagHelper to use the TagBuilder class when making the html nodes. 

- Uses TagBuilder
    - This always provides well-created nodes
    - Use `IHtmlGenerator.GeneratePageLink()` to create the anchor tag instead. This is what the AnchorTagHelper uses. 
- Fixes html node logic (no ending `</li>` tags)
 - Adds summary comments so that you get helper documentation when composing the `<pager>`  tag in a smart editor (like VS)
- Adds `asp-page` as a parameter to the `PagerTagHelper`
    - This replaces the hard-coded `./All` but should never have to be used with the current page. In fact I can't think of a reason to have it, but I left it in anyway to show where it goes in the GeneratePageLink.

## Adds `PageNumber` to the route ##
Instead of passing `PageNumber` through the `querystring` it is now passed through the route (a better ASP.NET Core pattern).

This is achieved in 3 simple steps:
  - Add to the **cshtml** page
```
    @page "{PageNumber?}"
```
  - Add to the **OnGet()** Razor class
```
    OnGet(int PageNumber = 1)
```
  - Decorate the PageNumber property with **[FromRoute]**
```
    [FromRoute]
    public int PageNumber { get; set; }
```

### CODE REVIEW

**Comment by csharpfritz** [comment]
The code as it is right now forgets the pagesize when you navigate from page to page

**Comment by smabuk** [comment]
I didn't mean to push the last commit. Not sure how to back out from it in a pull request.

It was really for final testing, and as a start to this feature.
Ideally the page size should get stored in the user profile, which we don't have yet.

**Comment by smabuk** [comment]
## Design issues ##

At this point there is little to no error checking in this TagHelper, and design decisions should be made going forward:
  - How to display once the number of pages gets beyond a certain limit.
      - Maybe something like | 1 | ... | 13 | **14** | 15 | ... | 50 | ... | 100 | etc. There are lots of different implementations around.
  - What to do if the current page number is greater than TotalPages
    - ... also a decision for the calling page which will be beyond the end of the articles.
  - make sure the design is responsive and works with the major browsers properly

Probably some others I haven't thought of yet.

**Comment by csharpfritz** [comment]
Let's take those design discussions to another issue, and we can work on them in additional pull requests

**Comment by csharpfritz** [comment]
Thanks for the contribution!

**Pull request merged**
